language: go
notifications:
  email: false
go:
  - 1.15
before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
before_script:
  - export TZ=Asia/Tokyo
  - sudo timedatectl set-timezone Asia/Tokyo
  - timedatectl
script:
  - make test
after_success:
  - goveralls -service=travis-ci
before_deploy:
  - GO111MODULE=off go get github.com/mitchellh/gox
  - GO111MODULE=off go get github.com/tcnksm/ghr
deploy:
  provider: script
  script: ./scripts/release.sh
  on:
    tags: true
    branch: master
