language: go
sudo: false
notifications:
  email: false
go:
  - 1.9
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
before_script:
  - export TZ=Asia/Tokyo
  - sudo timedatectl set-timezone Asia/Tokyo
  - timedatectl
script:
  - make test
branches:
  only:
    - master
after_success:
  - echo "TODO release process"
  # - gox -os "darwin linux windows" -arch "amd64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" .
  # - ghr --username tsuyoshiwada --token $GITHUB_TOKEN --replace `grep 'Version =' version.go | sed -E 's/.*"(.+)"$$/\1/'` dist/
