[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/tsuyoshiwada/go-gitcmd"
  version = "0.0.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.2"
