name: ci

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths-ignore:
      - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

env:
  GO_VERSION: "1.19"
  GOLANGCI_VERSION: "v1.50.1"

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test

      - name: Install goveralls
        run: go get github.com/mattn/goveralls
        env:
          GO111MODULE: off

      - name: Send coverage
        run: goveralls -coverprofile=cover.out -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: BGmi/BGmi
          fetch-depth: 0 # all history
          path: BGmi
          ref: v2.2.18
      - name: Test setup
        run: |
          docker version
          docker info
          pwd
          ls -lash
      - name: Test docker images of git-chglog
        run: |
          cd $GITHUB_WORKSPACE/BGmi
          docker run -v $(pwd):/workdir quay.io/git-chglog/git-chglog:0.15.2
