name: ci

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths-ignore:
      - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

env:
  GO_VERSION: "1.19"
  GOLANGCI_VERSION: "v1.50.1"

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test

      - name: Install goveralls
        run: go get github.com/mattn/goveralls
        env:
          GO111MODULE: off

      - name: Send coverage
        run: goveralls -coverprofile=cover.out -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_VERSION }}

  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest later
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run build
        run: make build
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: BGmi/BGmi
          fetch-depth: 0 # all history
          path: BGmi
          ref: v2.2.18
      - name: Test changelog generation with raw binary
        run: |
          cp ${GITHUB_WORKSPACE}/git-chglog ${GITHUB_WORKSPACE}/BGmi/git-chglog && chmod +x ${GITHUB_WORKSPACE}/BGmi/git-chglog 
          cd ${GITHUB_WORKSPACE}/BGmi
          ./git-chglog > raw.md
          head raw.md
          cd ${GITHUB_WORKSPACE}
      - name: Updating and upgrading brew
        if: matrix.os == 'macos-latest'
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew --version
      - name: Install and start docker
        if: matrix.os == 'macos-latest'
        # https://github.com/docker/for-mac/issues/2359#issuecomment-943131345
        run: |
          # for the docker cli
          brew install docker
          # installed by default
          colima start
      - name: Test setup
        run: |
          docker version
          docker info
      - name: Test docker images of git-chglog
        run: |
          ls -lash ${GITHUB_WORKSPACE}/BGmi
          # works
          docker run -v ${GITHUB_WORKSPACE}/BGmi:/workdir -w /workdir quay.io/git-chglog/git-chglog:0.15.1 > ${GITHUB_WORKSPACE}/BGmi/0151.md
          head ${GITHUB_WORKSPACE}/BGmi/0151.md
          # test current build
          docker build -t git-chglog:fix .
          docker run -v ${GITHUB_WORKSPACE}/BGmi:/workdir -w /workdir git-chglog:fix > ${GITHUB_WORKSPACE}/BGmi/fix.md
          head ${GITHUB_WORKSPACE}/BGmi/fix.md
          ## broken
          #docker run -v ${GITHUB_WORKSPACE}/BGmi:/workdir -w /workdir quay.io/git-chglog/git-chglog:0.15.2 > ${GITHUB_WORKSPACE}/BGmi/0152.md
          #head ${GITHUB_WORKSPACE}/BGmi/0152.md
