name: tests

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
jobs:
  unit:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - 
        name: Run tests
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          make test
          make coverage
      - 
        name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          path-to-lcov: cover.out
          github-token: ${{ secrets.GITHUB_TOKEN }}